export const FETCH_CATEGORY_LIST = "FETCH_CATEGORY_LIST";
export const FETCH_CATEGORY_LIST_SUCCESS = "FETCH_CATEGORY_LIST_SUCCESS";
export const FETCH_CATEGORY_LIST_ERROR = "FETCH_CATEGORY_LIST_ERROR";

export const FETCH_PRODUCT_LIST = "FETCH_PRODUCT_LIST";
export const FETCH_PRODUCT_LIST_SUCCESS = "FETCH_PRODUCT_LIST_SUCCESS";
export const FETCH_PRODUCT_LIST_ERROR = "FETCH_PRODUCT_LIST_ERROR";

export const FETCH_PRODUCT_ITEM = "FETCH_PRODUCT_ITEM";
export const FETCH_PRODUCT_ITEM_SUCCESS = "FETCH_PRODUCT_ITEM_SUCCESS";
export const FETCH_PRODUCT_ITEM_FAILURE = "FETCH_PRODUCT_ITEM_FAILURE";
